name: Deploy to Azure Container Apps

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  RESOURCE_GROUP: idea-hub-rg
  LOCATION: northeurope
  BACKEND_APP_NAME: aideahub-api
  FRONTEND_APP_NAME: ideahub-frontend
  ACR_NAME: ideahubappregistry
  CONTAINERAPPS_ENV: ideahub-env
  BASE_NAME: ideahub

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Derive tags
        id: vars
        run: |
          echo "sha_short=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: ACR Login
        run: az acr login --name $ACR_NAME

      - name: Build Backend Image
        run: |
          docker build -t $ACR_NAME.azurecr.io/ideahub-backend:${{ steps.vars.outputs.sha_short }} -f backend/Dockerfile .
      - name: Build Frontend Image
        run: |
          docker build -t $ACR_NAME.azurecr.io/ideahub-frontend:${{ steps.vars.outputs.sha_short }} -f frontend/Dockerfile .

      - name: Push Images
        run: |
          docker push $ACR_NAME.azurecr.io/ideahub-backend:${{ steps.vars.outputs.sha_short }}
          docker push $ACR_NAME.azurecr.io/ideahub-frontend:${{ steps.vars.outputs.sha_short }}

      - name: Deploy / Update Container Apps via Bicep
        run: |
          az deployment group create \
            -g $RESOURCE_GROUP \
            --template-file infra/main.bicep \
            --parameters backendImageTag=${{ steps.vars.outputs.sha_short }} frontendImageTag=${{ steps.vars.outputs.sha_short }} secretKey='${{ secrets.SECRET_KEY }}' \
              existingContainerAppsEnvironmentName=$CONTAINERAPPS_ENV existingAcrName=$ACR_NAME existingLogAnalyticsName=workspace-ideahubrg2Sa4

      - name: Show Outputs
        run: |
          az deployment group show -g $RESOURCE_GROUP -n main -o jsonc | sed -n 's/.*"value": "\(.*\)".*/\1/p' | head -n 5

      - name: Post Deploy Info
        run: |
          echo "Backend revision list:" && az containerapp revision list -n $BACKEND_APP_NAME -g $RESOURCE_GROUP -o table
          echo "Frontend revision list:" && az containerapp revision list -n $FRONTEND_APP_NAME -g $RESOURCE_GROUP -o table
